name: deploy

on:
  push:
    branches: [main]
    paths:
        - '.github/workflows/deploy.yml'
        - 'src/olm/**.py'
        - 'pyproject.toml'
        - 'uv.lock'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push container image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        file: Dockerfile
        tags: ${{ steps.login-ecr.outputs.registry }}/olm:latest,${{ steps.login-ecr.outputs.registry }}/olm:${{ github.sha }}
