name: deploy

on:
  push:
    branches: [main]
    paths:
        - '.github/workflows/deploy.yml'
        - 'src/olm/**.py'
        - 'pyproject.toml'
        - 'uv.lock'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR (latest)
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPO: olm
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build . -t $REGISTRY/$REPO:latest .
        docker push $REGISTRY/$REPO:latest
